### ISSUE TITLE
User session is replicating for all visitors to the website when first user logs in

### ISSUE THREAD

**Issue by nishtechgithub** [InsiteSoftware/commerce-csharp-sdk#95]
If I use this SDK to authenticate against Optimizely Configured Commerce, the authentication session replicates for all visitors to the website that's using this SDK. To recreate the problem we have taken the demo app https://github.com/InsiteSoftware/commerce-csharp-sdk/tree/main/CommerceApiSDK.DemoApp and used swagger. Please find the steps for recreating the issue in the below document.

[Steps to reproduce the login session issue.docx](https://github.com/InsiteSoftware/commerce-csharp-sdk/files/10708040/Steps.to.reproduce.the.login.session.issue.docx)

**Comment by himadric** [comment]
Any updates on this issue?

**Comment by himadric** [comment]
Is there any updates on this issue?

**Comment by johngofett** [comment]
Reopening - prematurely closed.

**Comment by anayaian** [comment]
Fix is merged with main branch. Nuget package (0.1.37) is updated with the fix as well.
