### ISSUE TITLE
After user logged out from the website, but the session shows it is active

### ISSUE THREAD

**Issue by sbsheik** [InsiteSoftware/commerce-csharp-sdk#97]
When user logged in and the new session is on. Later user logged out from the site, and then making current session request, it retrieves the current user info which makes user to be active on the site.

**Comment by anayaian** [comment]
@sbsheik  Correct me if I am wrong. This seems like the issue you are referring to:  https://github.com/InsiteSoftware/commerce-csharp-sdk/issues/95
PR: https://github.com/InsiteSoftware/commerce-csharp-sdk/pull/106

**Comment by sbsheik** [comment]
Yes, I am guessing  #95 will resolve the issue but have to confirm with latest version.

**Comment by anayaian** [comment]
Issue has been tested and addressed #95 . Please use the latest version of the SDK. A new sample demo has been provided for this. Will create a separate ticket to include that demo with this project for future reference.
