### ISSUE TITLE
SDK is returning null when optimizely configured commerce returns other status than 200K

### ISSUE THREAD

**Issue by sbsheik** [InsiteSoftware/commerce-csharp-sdk#99]
As of now SDK is capturing the response from the configured commerce only when 200K status is received, for other status it is returning null.
There are scenarios where the configured commerce api returns user friendly message on other status which is needed. Here is an example: 
Promotion api -   /api/v1/carts/current/promotions/carts/current/promotions
There is scenario for promotion api, when we are trying to apply same promotion twice to the cart then response from the api is 400 bad request with error message saying the _promotion is already added._ 
 
This applies to other status as well.

**Comment by anayaian** [comment]
I believe this issue has already been addressed when we merged #112
